### ISSUE TITLE
Describe FAIR

### ISSUE THREAD

**Issue by mpejcoch** [metno/S-ENDA-documentation#136]
Write a documentation page about what is FAIR

**Comment by ferrighi** [comment]
Do we just want a general introduction to FAIR/data sharing/open science or a more specific walk through each principle?

**Comment by mortenwh** [comment]
Isn't the more specific walk described in other websites? Maybe better with a general introduction and a link to a more "authoritative" site?

**Comment by ferrighi** [comment]
Yes, I agree. There are plenty of sources we can link to. Maybe I'll try to include some concept from the S-ENDA project plan. Then you can review.

**Comment by ferrighi** [comment]
Is there a specific place in the documentation where you want me to include this page?

**Comment by mortenwh** [comment]
Put them before the architecture and add a heading "FAIR principles" as first section in the content list. It should be very clear that these are our guiding principles to reach the goal of unified data management.

**Comment by mpejcoch** [comment]
Håvard pointed me recently to this: https://documentation.divio.com/ if that could help.
