### ISSUE TITLE
Create benchmarks for S-ENDA metadata service

### ISSUE THREAD

**Issue by mpejcoch** [metno/S-ENDA-documentation#140]

**Comment by mpejcoch** [comment]
Currently the full NBS archive takes ~2h to be ingested into pyCSW (with postgres backend) on a laptop 1.6G MHz 4 cores/8 threads CPU

**Comment by epifanio** [comment]
Workflow:

* clone NBS SVN repository
* convert mmd to iso
* fixing iso tags
    - add `.html` to opendap resource URL
    - use the tag: `OGC:WMS` to specify a `WMS` resource
    - fix the getcapabilities URL 
    - for ['S2A'] replace wms to wms_jpeg
    - for ['S1A', 'S2B', 'S1B', 'S2B'] compelte the URL with the getcapabilities request.

* PyCSW indexing - [Total number of records: 318525]
```
    Total time: ~ 112m

    real 102m57.252s

    user 53m49.748s

    sys 2m13.839s
```
Notes:

`mmd2iso` conversion and `Isofix took` ~10', not including the `svn clone` step

The platform used: 
- laptop with 4CPU at 1.6GhZ each, all processes (conversion, fixing and indexing) have been executed in parallel for a total of 8 threads. 
- All the processes were running from a Docker environment.
- The laptop has been normally used during the processing which could have negatively impacted the run-time to complete the indexing process) 
- No excessive use of memory has been noticed

**Comment by mortenwh** [comment]
@mpejcoch - please reopen if necessary...
