### ISSUE TITLE
Consider pure pyCSW architecture of S-ENDA Find

### ISSUE THREAD

**Issue by mpejcoch** [metno/S-ENDA-documentation#144]

**Comment by mortenwh** [comment]
Are we able to index MMD directly, and not only ISO19115?

**Comment by mortenwh** [comment]
shouldn't this be added to the sprint backlog?

**Comment by mortenwh** [comment]
See "Dynamic Geo-Assets Component Diagram" based on sprint 1 and "PyCSW component diagram" (currently in branch issue142_alternative_container_diagrams). It seems clear that this is the way to go, so I'm closing this issue. Please reopen if you disagree.

@mpejcoch @epifanio @ferrighi

**Comment by mpejcoch** [comment]
I meant using pyCSW as a metadata store and inserting into it using "Transactions": https://docs.pycsw.org/en/2.4.2/transactions.html#transactions

**Comment by mortenwh** [comment]
Ok, can you explain that in more detail? Do you mean that pycsw should be the authoritative source, and that the MMD XML should be removed? Can you create an alternative container diagram and pycsw component diagram, and add them to the architecture document in branch `issue142_alternative_container_diagrams`?

**Comment by ferrighi** [comment]
I think that you should not remove the possibility to index in iso to start with, as that is the fastest way to go. The mmd plugin, as far as we discussed requires more time and it seems it is a longer term, although preferred solution. 
Concerning the authoritative source, I think that should necessarily be a version controlled repository.
