### ISSUE TITLE
Reusability of the developer portal

### ISSUE THREAD

**Issue by havardf** [metno/S-ENDA-documentation#150]
In order for the yr developer portal to be reused, we need to give code and config an open source license?

Can we do that? Which license? Who decides? What do we do if thats not possible?

ROS analyses of open sourcing the developer portal?

**Comment by havardf** [comment]
To hovedkomponenter her:
- Metadata for allmennheten data, så de blir synlige i google og på data.norge.no/https://fellesdatakatalog.digdir.no/, geonorge.no
- Utviklerportal, som gjør det enkelte å bruke apiene og dataene ,og kommunisere tilbake.

**Comment by mortenwh** [comment]
can you move this epic to the priority epics pipeline? I didn't want to do it, in case I would mess up something :)
