### ISSUE TITLE
Open source license for yr developer-portal

### ISSUE THREAD

**Issue by havardf** [metno/S-ENDA-documentation#155]

**Comment by havardf** [comment]
In order for the setup of our developer portal to be reusable for others, especially other organizations involved in S-ENDA, we need an open source license.

That license must allow the user to copy and modify our setup. But we must ensure that the license do not give the user rights to reuse trademarked logo and fonts, even if the logo image is present in the repository.

Also, in general that they are not allowed to try to use the developer portal setup to try to impersonate Yr, api.met.no etc.

**Comment by mortenwh** [comment]
Can you provide a link to the license?
