### ISSUE TITLE
Agree on the format of the use case descriptions

### ISSUE THREAD

**Issue by mortenwh** [metno/S-ENDA-documentation#17]
At the moment, the use case template is in reStructuredText (rst) format. There are at least two other optional formats that we could use; MarkDown and AsciDoc. Under this issue, we open up for a discussion about the choice of format. Some arguments follow.

# reStructuredText

* reStructuredText integrates with sphinx and readthedocs
* readthedocs is a well-known and commonly used site for documentation of open-source projects
* sphinx can handle uml (see, e.g., https://build-me-the-docs-please.readthedocs.io/en/latest/Using_Sphinx/UsingGraphicsAndDiagramsInSphinx.html)
* readthedocs integrates with GitHub (i.e., every new commit and version tag in the master [or other] branch automatically results in a new version of the formatted version at readthedocs)
* you can download the documentation in pdf, html and epub formats from readthedocs

# AsciiDoc

* asciidoc is used for the cf-conventions (see https://github.com/cf-convention/cf-conventions)
* asciidoc is used for the MMD convention (see https://github.com/steingod/mmd)
* asciidoc (diagram extension) used with, e.g., GraphViz, can be used to add diagrams (uml)
* asciidoc can also handle mathematical expressions (see, e.g., https://www.methods.co.nz/asciidoc/chunked/ch25.html)
* asciidoc does not integrate with readthedocs
  * does it integrate with another online service?

# MarkDown

* MarkDown is simpler and does almost the same as rst and asciidoc
* MarkDown is already widely used for documentation at MET(?)
* GitHub supports markdown

# Integration with PlantUML
* https://plantuml.com/
* Easy syntax
* Readable and editable

**Comment by mpejcoch** [comment]
Can you add plantuml to the list?

**Comment by mpejcoch** [comment]
If we don't see it as probable that we will need some more advanced formatting that AsciiDoc can offer I would go for MarkDown as it's the simplest one and well integrated with both GitHub and GitLab. I think that the reStructuredText syntax is unnecessarily heavy, i.e., writing so many "=" for every heading looks cumbersome.

I see now that PlantUML does not directly compare with the first 3, rather it can be combined with them.

**Comment by mpejcoch** [comment]
I'll check if the UML integration works with Markdown.

**Comment by mpejcoch** [comment]
Looks like it should work, but won't be straightforward: https://sphinx-doc-template.readthedocs.io/en/latest/markdown.html

**Comment by mortenwh** [comment]
It seems we agree on the current system, so I'm closing this issue now.
