### ISSUE TITLE
S-ENDA metadata service

### ISSUE THREAD

**Issue by mortenwh** [metno/S-ENDA-documentation#174]
Is it more correct to name it S-ENDA discovery metadata service?

**Comment by niellaNina** [comment]
I am thinking that S-ENDA discovery metadata service is a better name. Metadata can be so much more and by using just "Metadata" in the name it might be misleading for users if they are looking for something the discovery metadata does not deliver.

**Comment by mortenwh** [comment]
Yes, this makes more sense. I'll close this issue now. If anyone disagrees - please reopen and complain :)

**Comment by mortenwh** [comment]
Actually - the repository for this is called `S-ENDA-csw-catalog-service` now... Should this be reflected in the architecture? @mpejcoch - what do you think makes more sense?

**Comment by mortenwh** [comment]
Architecture documents can stay as they are. There is no need for direct linking between repo names and drawings..
