### ISSUE TITLE
Add documentation for syntax and linting checking for Python code and update the DoD

### ISSUE THREAD

**Issue by vkbo** [metno/S-ENDA-documentation#191]
Proposal to add automatic code syntax and style check requirements for Python repos to the documentation.

I have a summary of my own configuration based on `flake8` that I use for my repos listed here as an example: https://github.com/vkbo/vkbo/blob/main/python_style.md

This example includes a working GitHub actions yaml (just edit the branches if needed), and configs that can be read by a local `flake8`. For VSCode, the `cornflakes-linter` plugin runs these checks in the background when a file is saved.

This workflow has already been added to [py-mms](https://github.com/metno/py-mms).

**Comment by johtoblan** [comment]
Is this the correct milestone?

**Comment by mortenwh** [comment]
I think this can be closed. It is covered in MMS but we need to gradually implement it in other repositories. In any case, the culture around testing is quite well established.
