### ISSUE TITLE
Describe interface for provenance data for distribution services

### ISSUE THREAD

**Issue by havardf** [metno/S-ENDA-documentation#198]

**Comment by mortenwh** [comment]
@havardf - can you clarify what needs to be done here?

**Comment by havardf** [comment]
I am a bit rusty about the context here. I think though it relates to the more general problem about how custom distribution services, like the frost and api.met.no should provide metadata about how their data was produced.

Eg. should the service itself provide a DCAT-AP-NO v.2.0 document describing the service, its data and the provenance of its data? Or is it best to expect those kinds of metadata to be produced, distributed and presented by another channel, e.g the same channel that is used for registering metadata for netcdf-datasets and such.

So the issue is not just about describing the interface, but figuring out what such an interface should be.

**Comment by niellaNina** [comment]
Fjerner denne fra epic L5.4 ... Havner litt på siden av den og da kan den epicen lukkes
