### ISSUE TITLE
User quality control of data

### ISSUE THREAD

**Issue by lcoram** [metno/S-ENDA-documentation#215]
What is the metadata needed for users to understand quality control that has been performed on data. 
Should it be possible to give feedback on datasets regarding the quality of parts of the data?

**Comment by niellaNina** [comment]
After investigating the international standards for data quality on the discovery level (focused on ISO 19157 and DQV from DCAT) we concluded:

- Both standards have a lot of elements/classes etc. all (that are only related to quality) are optional.
- Many of the elements/classes in the standards may prove to be complicated for data producers to generate (so they may not be generated at all) and may not be useful for many data consumers (so they may not be used at all)
- Our need is something simpler, more a description of if the data is quality controlled or not, possibly with a link to a description of the quality control that has been done.
- We can add this type of information and still use the standards as both standards have a form of descriptive element/class (free form text).

We decided to do the following:
- Add a quality elment to the MMD standard that mapped to appropriate elements in the standards.
- Set up a local (MET) controlled vocabulary for the free text. This controlled vocabulary should be a short list (max 6-7 items) along the lines of "Not quality controlled", "Basic quality control", ... "Extensive quality control, both automatic and manual"

**Comment by niellaNina** [comment]
somehow added comment to the wrong issue... sorry

**Comment by niellaNina** [comment]
Regarding this: 
"What is the metadata needed for users to understand quality control that has been performed on data."

This will be the new MMD element for data quality (see issue #114 in the mmd repo), a new controlled vocabulary for this MMD element that will be made available at vocab.met.no will be created for this element.

Regarding the second part:
"Should it be possible to give feedback on datasets regarding the quality of parts of the data?"

I think this could be a nice feature, and there is a possibility for adding this sort of information in the DQV standard, that may be added to the MMD specification. However, to fully use this we need to look into systems for handling this type of user information:
- where shall it be added?
- should it only be for "advanced/scientist users" who are finding the data through the tools we are creating in SENDA, or should also more internal user feedback be added? (possibly more complex/more work)

My suggestion now is to close this issue, create a new for the user feedback and put that one in the icebox for later consideration.

**Comment by niellaNina** [comment]
The task about user feedback has been created #260 and added to the icebox.
