### ISSUE TITLE
Use case: Arome arctic nwp model

### ISSUE THREAD

**Issue by havardf** [metno/S-ENDA-documentation#220]
What is the work flow for producing arome arctic datasets?
By whom and how are the different datasets consumed?

**Comment by havardf** [comment]
I got some information about the use of arctic datasets from Eivind Støylen:

**Users:**
 - Havmodellene bruker den som inn-data (usikker på om de leser fra lustre eller thredds)
- En rekke studenter/phd/forskere på e.g. UNIS bruker modelldataene i prosesstudier, de henter data fra thredds over opendap
- yr som du nevner
- det finnes noen tjenester som e.g. fiskinfo / barentswatch som bruker data via thredds (kanskje de henter wms-kart)
- grunnlagsdata for SIMRA modellen i longyearbyen, en dedikert turbulensmodell som avinor benytter. Dette er en del av arome-arctic post-produksjonen.

**Arome-Arctic er delt inn i to "produkter" på thredds: Latest og Archive. Hva er forskjellen på disse:**
Latest er bare en symlink, det er det samme filinnholdet som ligger i filene med DTG i filnavnet under https://thredds.met.no/thredds/catalog/aromearcticlatest/catalog.html . 
Filene under  https://thredds.met.no/thredds/catalog/aromearcticarchive/catalog.html er bare kopier av filer fra latest. Arkivet slettes ikke, men latest katalogen sparer bare noen få dager. 
Vi har mange brukere som bruker eldre data. Jeg vet ikke akkurat hvordan folk setter ting opp, men mange er ute etter en tidsserie eller spesielle caser fra en gitt dato. 
Kan nok hende noen er ute etter nyeste data men bruker ikke "latest" navnet. Dette kan være fordi vi ber brukere av latest meps om å bruke filer med dtg i navnet, dette pga at vi har ncml-filer på https://thredds.met.no/thredds/catalog/mepslatest/catalog.html  , og thredds er noen ganger treg med å oppdatere pekeren til latest slik at den ikke faktisk peker til den nyeste fila (når filer oppdateres ofte (e.g. hver time) blir det et problem. 

**Støtter arome arctic datasettene en lang sømløs tidsserie?**
Nei, det jeg mener brukerne gjør er at de henter ut værvarsel fra mange modellkjøringer etter hverandre.  Vi vil ikke lage en sømløs tidsserie som datasett. Poenget er at for en del parametre så blir det feil å betrakte tidsserien som sømløs siden det kommer nye analyser og nye randverdier, slik at ting som nedbør (eller vannmengde i lufta) ikke vil være konsistent fra et tidspunkt til det neste.

**Comment by mortenwh** [comment]
This one is not needed anymore
