### ISSUE TITLE
Update Data Management Recipes section

### ISSUE THREAD

**Issue by ElodieFZ** [metno/S-ENDA-documentation#226]
Update the Data Mangement Recipes: add checking that the necessary fields from input netcdf files are present in order to generate a valid MMD file. Describe validating tool from [https://github.com/metno/py-mmd-tools](url).

**Comment by mortenwh** [comment]
Covered by https://app.zenhub.com/workspaces/s-enda-5e7b1b4acfc5ca185fb6b53c/issues/metno/s-enda-documentation/238
