### ISSUE TITLE
Agree output profile with GeoNorge (INSPIRE?)

### ISSUE THREAD

**Issue by ferrighi** [metno/S-ENDA-documentation#235]

**Comment by ferrighi** [comment]
Contact GeoNorge and get feedback

**Comment by mortenwh** [comment]
I have set up a meeting with Kartverket on Friday

**Comment by mortenwh** [comment]
Agreed about INSPIRE but with national extensions. We will create xml files that they can can check, and we'll have a dialog around that.

- Trygve will write an MMD file for one instrument, and collect xml files for some acquisitions (children) from that instrument
- we will translate to INSPIRE
- then we'll iterate with Kartverket...
