### ISSUE TITLE
DMH: Split documentation in General part and Specific part (MET)

### ISSUE THREAD

**Issue by niellaNina** [metno/S-ENDA-documentation#241]

**Comment by mortenwh** [comment]
DMH git repo: https://github.com/metno/data-management-handbook

**Comment by ElodieFZ** [comment]
@niellaNina All the text has been splitted between MET specific and general in https://docs.google.com/document/d/1LIKrtGtdQEW8Kn46f_sWPoLU3RophisS4IsgpNygnUg . So I moved the issue to Review, but maybe it should be left open until all the text is moved to the DMH git repo? What do you think?

**Comment by niellaNina** [comment]
@ElodieFZ I think we can close this. The separate parts of the DMH is/will be other issues
