### ISSUE TITLE
Deploy PyCSW container in Kubernetes

### ISSUE THREAD

**Issue by epifanio** [metno/S-ENDA-documentation#244]

**Comment by epifanio** [comment]
Set up documentation on how to deploy a PyCSW container into the met Kubernetes infrastructure.

**Comment by aheimsbakk** [comment]
I've added a local copy of PyCSW to GitLab s-enda/pycsw.

We have at the moment auto-deploy of PyCSW into Kubernetes into dev and staging environment from our local copy of PyCSW repository. We need to find out if we develop against it manage to push changes upstream.
