### ISSUE TITLE
CSW getcapabilities returns wrong links in dev and (probably) staging

### ISSUE THREAD

**Issue by mortenwh** [metno/S-ENDA-documentation#251]
The links refer to the production environment, and the production env is not up yet.

- [ ] Links in staging should refer to staging, etc

**Comment by TAlonglong** [comment]
`curl 'https://csw-dev.s-enda.k8s.met.no/pycsw/csw.py?service=CSW&version=2.0.2&request=GetCapabilities' | xmllint --format - > csw-dev-getcapabilities.txt`
[https://app.zenhub.com/files/227606604/4b62f376-c70a-4d0a-9ad9-3d8c77822ab6/download](https://app.zenhub.com/files/227606604/4b62f376-c70a-4d0a-9ad9-3d8c77822ab6/download)
