### ISSUE TITLE
check evaluation report to fix mmd records

### ISSUE THREAD

**Issue by ferrighi** [metno/S-ENDA-documentation#255]
check evaluation report as mmd for satellite data still have some issues, with for example multi language entries.

**Comment by TAlonglong** [comment]
I had a quick look at this https://docs.google.com/document/d/1IcLVnUJgFEnGcGp2iP29TGFLoNEV-WzK9w96rFUTR2s/edit#, but I can't see anything related to this.

Is this the correct document you are refering to @ferrighi?

**Comment by ferrighi** [comment]
in the satellite session it is mentioned title and abstract, we have an issue here: https://github.com/metno/py-mmd-tools/issues/78 
I think from my side I should also change the xslt as now I only pick up xml:lang = "no", but I should pick up also your "nob".

**Comment by TAlonglong** [comment]
Ah, thanks

**Comment by TAlonglong** [comment]
I'm not sure, but I think this is done in #254 

But we have nothing on `nob`. Is this something we should add? like
`title_nob=<bladibla>`
`abstract_nob=<bladibla>`

in addition to title_no and abstract_no?

**Comment by ferrighi** [comment]
No, I think we are done. You do not need to provide nob. I do that when translating to geonorge. You are good with only title_no and abstract_no.

**Comment by mortenwh** [comment]
@TAlonglong - is this done now?

**Comment by TAlonglong** [comment]
Yes. I guess if we need more fixes we either make new issues or reopen this one
