### ISSUE TITLE
Features needed for mapserver for S-ENDA (NBS)

### ISSUE THREAD

**Issue by TAlonglong** [metno/S-ENDA-documentation#269]
Investigate setting up mapserver to serve the needs of S-ENDA and maybe also NBS.

**Comment by TAlonglong** [comment]
Contact the NBS team to gather design of the exiting NBS system using mapserver. And also collect experiences with the system (mapserver used in NBS) and wish for new features.

**Comment by ferrighi** [comment]
I've collected a short documentation abut this, which Øystein has reviewed for NBS. @TAlonglong you have already gotten feedback from Trond, but feel free to comment/add on the document:
https://docs.google.com/document/d/1SaWI4LDPmY_Jyuebmt5g7fQZG5-uxSrdc5ctqDjdPO0/edit#
