### ISSUE TITLE
automatic conversion of frost-oda to netcdf

### ISSUE THREAD

**Issue by ElodieFZ** [metno/S-ENDA-documentation#271]
Where and how will the conversion happen?

**Comment by lcoram** [comment]
Containerize and make into a cron job on K8s

**Comment by lcoram** [comment]
Will run python scrip on PPI and push to lustre to have files exposed on Thredds

**Comment by ElodieFZ** [comment]
The repo containing all the oda to nc code is in gitlab [https://gitlab.met.no/louiseo/oda-to-netcdf](here)

**Comment by mortenwh** [comment]
can you move the repo to a private github one? This will make it easier to keep track of the progress..

**Comment by ElodieFZ** [comment]
The code is now on github at https://github.com/metno/oda2mmd
The code will run on PPI via cron.
Cron is currently set to run every 6 hours. Can be easily changed.
I will run the code that creates both nc and mmd files with my account on PPI.
The outputs will be written on a directory owned by obsklim.
