### ISSUE TITLE
Preparatory work

### ISSUE THREAD

**Issue by mortenwh** [metno/S-ENDA-documentation#275]

**Comment by TAlonglong** [comment]
This work has led to a prototype of the wanted setup.
A  docker container has been made with mapserver and apache2. https://gitlab.met.no/trygveas/okd-satellite-mapserver-image. No caching is applied yet. So this needs to be implemented as needed at a later stage. This can be mapcache, mapproxy (https://mapproxy.org/) or general cache like varnish.
Also a k3s(minicube) setup has been setup at my laptop inside a vagrant instance. This is very similar to the vagrant-senda which has been used as a stating point. Thank you Arnulf for this setup. https://gitlab.met.no/trygveas/vagrant-senda-mapserver
With this setup you need to sync data inside the persistent storage, generate unique map file for this data and update the mmd xml file with the new OGC WMS service. Please see script https://gitlab.met.no/trygveas/vagrant-senda-mapserver/-/blob/master/scripts/py-mmd-edit-resource.py how this can be done.
