### ISSUE TITLE
setup mapserver in kubernetes

### ISSUE THREAD

**Issue by TAlonglong** [metno/S-ENDA-documentation#279]

**Comment by TAlonglong** [comment]
https://ticket.met.no/rt/Ticket/Display.html?id=138206

Namespace is now available https://gitlab.met.no/tjenester/s-enda-ogc

This is the first iteration which I presume needs to be iterated as needed

**Comment by mortenwh** [comment]
Did you discuss this with @aheimsbakk ? I'm unsure if it should rather be added in the s-enda namespace.. Also, I'm afraid s-enda-ogc is misleading. CSW is also an ogc standard...

**Comment by TAlonglong** [comment]
Ah, I did not think of that. Sorry.

No I did not discuss it with Arnulf as he was not available at that time.

I discussed with Christian Skarsby, and we decided on this.

**Comment by TAlonglong** [comment]
After a meeting with Arnulf, Morten, Massiomo and me, we decided to move this functionallity into the exiting S-ENDA Namespace.

The S-ENDA namespace will be complex, but each service run seperately and its a good thing to collect all the S-ENDA stuff in one namespace.

This will be done after the sprint.
