### ISSUE TITLE
Fix of dead link in mmd xml files for satellite data

### ISSUE THREAD

**Issue by TAlonglong** [metno/S-ENDA-documentation#282]
Check https://app.zenhub.com/workspaces/s-enda-5e7b1b4acfc5ca185fb6b53c/issues/metno/mmd/164 if need to update the existing mmd xml files already i pyCSW

**Comment by mortenwh** [comment]
I'm pretty sure it should be updated. Can you do it? And how is the workflow for this now? Is there a way we could help to make it easy for the data producers/owners? Or perhaps is should be the responsibility of someone else, like FoU-FD? Similar changes will be necessary quite often, I believe...? @ferrighi - any views?

**Comment by mortenwh** [comment]
Trenger å gjøre flere endringer i metadataene (f.eks. titler). Denne saken løses i samme forbindelse.
