### ISSUE TITLE
Specification of provenance metadata

### ISSUE THREAD

**Issue by mortenwh** [metno/S-ENDA-documentation#300]
@niellaNina - can you describe?

**Comment by niellaNina** [comment]
Suggested Plan:

- Use the PROV standard from W3C: https://www.w3.org/TR/prov-overview/
- Provenance metadata will be linked to but stored and distributed separately from the data and the (discovery) metadata
- Begin with some types of provenance metadata for some time-series (step by step approach)

**Comment by mortenwh** [comment]
Følges opp i partnersamarbeid
