### ISSUE TITLE
Use case: System owner want an UUID for input fetched from other organisation

### ISSUE THREAD

**Issue by janip** [metno/S-ENDA-documentation#32]
As the System owner for the service Volcanic ash forecast at MET I need to refer to input data fetched from NILU which has no DOI, so I need to create an UUID for this data, and the UUID must at least be valid inside MET Norway.

**Comment by mortenwh** [comment]
You need to use the NILU id of the dataset. Could be regular uuid or a doi. If none if these exist, NILU would need to create it.
