### ISSUE TITLE
Search API interfacing with a central system

### ISSUE THREAD

**Issue by mortenwh** [metno/S-ENDA-documentation#55]
Why doesn't API search from the users connect directly to S-ENDA find? If we implement pyCSW there, we could use opensearch directly as search interface, couldn't we @epifanio?

**Comment by mpejcoch** [comment]
The reasoning so far has been that most of the users wouldn't know that S-ENDA Find exists.

**Comment by mortenwh** [comment]
ok - but do we make the search API? maybe it can be expected that a user of the API would know about S-ENDA find? Or do we require usage via GeoNorge, and in that case develop it for GeoNorge?

**Comment by mpejcoch** [comment]
> ok - but do we make the search API? maybe it can be expected that a user of the API would know about S-ENDA find? Or do we require usage via GeoNorge, and in that case develop it for GeoNorge?

That I don't know, I think I only answered your first question :) For the other one I would need more information. Perhaps it will be provided by pyCSW as you have mentioned? Another candidate would be the Geo-Assets API (though only for registered users) - @havardf ?

**Comment by mortenwh** [comment]
I think we need to add a central system connecting several instances of S-ENDA find and access in a distributed data management context to the architecture. In principle, that central system could be GeoNorge or ADC but this can be kept. Then, the portals and the search API should connect to that. I'll make a suggestion..

**Comment by mortenwh** [comment]
@mpejcoch @epifanio @havardf 

See branch issue55_central_system - isn't this more complete? We need to think distributed data management...

I also realised that the DOI registration is not under S-ENDA responsibility. DOI task in WP6 is only for MET. The other data centres are responsible for their own datasets.

**Comment by mortenwh** [comment]
can this be closed now? @mpejcoch @havardf
